apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: mgharnish91-poi-map-app-dev
  annotations:
    argocd/app-name: mgharnish91-poi-map-app-dev
    backstage.io/kubernetes-id: mgharnish91-poi-map-app
    backstage.io/kubernetes-namespace: mgharnish91
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: rhdh-deploy/mgharnish91-frontend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - typescript
    - angular
    - workshop
  links:
    - url: https://console-openshift-console.apps.a1jxqhzp.eastus2.aroapp.io/dev-pipelines/ns/mgharnish91/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.a1jxqhzp.eastus2.aroapp.io/k8s/ns/mgharnish91/deployments/mgharnish91-poi-map-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.a1jxqhzp.eastus2.aroapp.io/#https://github.com/rhdh-deploy/mgharnish91-frontend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: http://mgharnish91-poi-map-app-mgharnish91.apps.a1jxqhzp.eastus2.aroapp.io
      title: Map
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/mgharnish91"
  system: workshop-system-mgharnish91
  consumesApis:
    - gateway-api-mgharnish91
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-mgharnish91
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/mgharnish91"
